version: '3.6'
services:
  iris:
    image: intersystemsdc/iris-community
    restart: always
    ports:
      - 1972
      - 55038:52773
    environment:
      - IRISUSERNAME=_SYSTEM
      - IRISPASSWORD=SYS
    volumes:
      - ./init.db/:/docker-entrypoint-initdb.d
      - ./:/home/irisowner/dev
